# Generated by Django 2.2 on 2020-04-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0003_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Category Title'),
        ),
    ]
