# Generated by Django 2.2 on 2020-04-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0004_auto_20200404_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='be unique', max_length=250, verbose_name='Category Title'),
        ),
    ]
