# Generated by Django 2.2 on 2020-04-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0005_auto_20200404_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
